version: '3.4'

services:
  daprfrontend:
    image: ${DOCKER_REGISTRY-}daprfrontend
    build:
      context: .
      dockerfile: DaprFrontEnd/Dockerfile
    ports:
      - "50000:50001"
    depends_on:
      - redis

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "daprfrontend", "-app-port", "80", "-components-path","/components" ]
    volumes:
      - ./components-compose/:/components
    depends_on:
      - daprfrontend

    network_mode: "service:daprfrontend"

  daprbackend:
    image: ${DOCKER_REGISTRY-}daprbackend
    build:
      context: .
      dockerfile: DaprBackEnd/Dockerfile
    ports:
      - "52000:50001"
    depends_on:
      - redis

  daprbackend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "daprbackend", "-app-port", "80", "-components-path","/components" ]
    volumes:
      - ./components-compose/:/components
    depends_on:
      - daprfrontend
    network_mode: "service:daprbackend"

  daprworker:
    image: ${DOCKER_REGISTRY-}daprworker
    build:
      context: .
      dockerfile: DaprWorker/Dockerfile
    ports:
      - "53000:50001"
    depends_on:
      - redis

  daprworker-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "daprworker", "-app-port", "80", "-components-path","/components" ]
    volumes:
      - ./components-compose/:/components
    depends_on:
      - daprworker
      - daprbackend
    network_mode: "service:daprworker"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
